#!/usr/bin/env bash
# Prevents editing files inside public/ (Hugo build output).
# public/ is fully regenerated by `make build` — edits there are silently wiped.
#
# Usage as an AI coding assistant hook (PreToolUse):
#   Tool input arrives as JSON on stdin; exits 2 to block with a message.
#
# Usage as a git pre-commit hook:
#   ln -s ../../scripts/hooks/block-public-edits.sh .git/hooks/pre-commit
#   When invoked by git, stdin is a terminal — the check is skipped automatically.

set -euo pipefail

# If stdin is a terminal (git hook context), nothing to check.
if [ -t 0 ]; then
  exit 0
fi

file_path=$(python3 -c "
import sys, json
try:
    print(json.load(sys.stdin).get('file_path', ''))
except Exception:
    print('')
" 2>/dev/null || echo "")

if [[ "$file_path" == public/* ]] || [[ "$file_path" == */public/* ]]; then
  echo "ERROR: Cannot edit files in public/ — it is Hugo build output." >&2
  echo "Edit source files in layouts/, assets/, static/, or content/ instead." >&2
  echo "Run 'make build' to regenerate public/ from sources." >&2
  exit 2
fi
